### ISSUE TITLE
v. 1.2.0: ERROR: Method "getModuleConfig" does not exist and was not trapped in __call()

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2-module-jira#77]
Hi all,
I updated all modules yesterday (because of Icingaweb 2.10). When I now try to create a Jira Ticket from Host or Service Views, I get
"ERROR: Method "getModuleConfig" does not exist and was not trapped in __call()"

Modules:
```
Icinga Web 2 Version	2.10.0
Git commit	f1dc03fd8553fe58ef85ca6fb607fe2922c3e078
PHP Version	7.4.3
Git commit date	2022-03-23

Loaded Libraries
icinga/icinga-php-thirdparty	0.10.0
icinga/icinga-php-library	0.8.0

Loaded Modules
businessprocess		2.4.0	Configure
grafana			1.4.2	Configure
idoreports		0.10.0	Configure
incubator		0.13.0	Configure
jira			1.2.0	Configure
monitoring		2.10.0	Configure
pdfexport		0.10.1	Configure
reporting		0.10.0	Configure
```

Cheers,
Marcus

**Comment by theFeu** [comment]
Hey there, could you send us a full stack trace of the issue?

**Comment by lippserd** [comment]
Hi @MarcusCaepio,

Thanks for the report. Could you please try the linked PR and report if that fixes the problem?

Cheers,
Eric

**Comment by MarcusCaepio** [comment]
Hi @lippserd 
Unfortunately not, but I got a Stacktrace now:

```
Uncaught Error: Class 'Icinga\Module\Jira\Web\Config' not found in /usr/share/icingaweb2/modules/jira/library/Jira/Web/Controller.php:19
Stack trace:
#0 /usr/share/icingaweb2/modules/jira/application/controllers/IssuesController.php(59): Icinga\Module\Jira\Web\Controller->getModuleConfig()
#1 [internal function]: Icinga\Module\Jira\Controllers\IssuesController->showNewIssueForm()
#2 /usr/share/icingaweb2/modules/jira/library/Jira/Web/Controller.php(45): call_user_func()
#3 /usr/share/icingaweb2/modules/jira/application/controllers/IssuesController.php(49): Icinga\Module\Jira\Web\Controller->runFailSafe()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Jira\Controllers\IssuesController->createAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#7 /usr/share/php/Icinga/Application/Web.php(304): Zend_Control

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

**Comment by lippserd** [comment]
Yeah, forgot an import 😆 Please try again.

**Comment by MarcusCaepio** [comment]
Now it's working. Thanks for the quick fix :)
