### ISSUE TITLE
Creating issues again not working after updating icinga2 + icingaweb2

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2-module-jira#83]
Hi all,
we updated icinga2 and icingaweb2 this week. Since then, ticket creation is not working again:

```
Uncaught Error: Class 'Icinga\Module\Monitoring\Backend' not found in /usr/share/icingaweb2/modules/jira/library/Jira/IdoBackend.php:26
Stack trace:
#0 /usr/share/icingaweb2/modules/jira/library/Jira/IdoBackend.php(55): Icinga\Module\Jira\IdoBackend->getObject()
#1 /usr/share/icingaweb2/modules/jira/application/controllers/IssuesController.php(79): Icinga\Module\Jira\IdoBackend->getMonitoringInfo()
#2 /usr/share/icingaweb2/modules/jira/application/controllers/IssuesController.php(54): Icinga\Module\Jira\Controllers\IssuesController->requireMonitoringInfo()
#3 [internal function]: Icinga\Module\Jira\Controllers\IssuesController->showNewIssueForm()
#4 /usr/share/icingaweb2/modules/jira/library/Jira/Web/Controller.php(46): call_user_func()
#5 /usr/share/icingaweb2/modules/jira/application/controllers/IssuesController.php(49): Icinga\Module\Jira\Web\Controller->runFailSafe()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Jira\Controllers\IssuesController->createAction()
#7

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```
The jira issues overview in the sidebar is still working. 

os: ubuntu 20.04.4
icinga2: r2.13.4-1
monitoring: 2.11.0
jira: 1.2.1

Cheers,
Marcus

**Comment by nilmerg** [comment]
v1.2.2 has just been released to fix this.
