### ISSUE TITLE
v1.2.2 Error: Not Found (w/ Jira SM 5.0.0)

### ISSUE THREAD

**Issue by dmueckli** [Icinga/icingaweb2-module-jira#85]
Hello all, 

I am currently trying to get version 1.2.2 (or master) running with jira service management version 5.0.0. When I try to inspect the Jira server through icingaweb I get the following error: 

"Not found"
```
#0 /usr/share/icingaweb2/modules/jira/library/Jira/RestApi.php(390): Icinga\Module\Jira\RestApi->request()
#1 /usr/share/icingaweb2/modules/jira/library/Jira/Web/Form/TemplateForm.php(56): Icinga\Module\Jira\RestApi->get()
#2 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(295): Icinga\Module\Jira\Web\Form\TemplateForm->assemble()
#3 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(497): ipl\Html\HtmlDocument->ensureAssembled()
#4 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\HtmlDocument->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#16 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#17 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#18 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#19 {main}
```

Also when I try to manually create an issue from host or services in Icinga I get the same error "Not found" but without a stacktrace.
![image](https://user-images.githubusercontent.com/58838393/177850528-bda33521-95ce-4ccb-b40c-d5e760aaaa7f.png)

I checked the config.ini for errors, but couldn't find any. 

However, ticket creation through notification as viewing the created tickets works.
![image](https://user-images.githubusercontent.com/58838393/178082729-b715730a-cf7b-423c-86d3-1201767b1bf7.png)

```
Icinga Web 2 Version	2.11.1
Git Commit	eecf8d9934cbf30ec063cea4a525b26bfd2bf99a
PHP-Version	7.4.30
Git Commit Datum	2022-07-06

Geladene Bibliotheken
icinga/icinga-php-thirdparty	0.11.0
icinga/icinga-php-library	0.9.1

Geladene Module
director		master
grafana		1.3.5	
icingadb		1.0.0	
incubator		0.17.0
jira		        1.2.2	
```

Thanks in advance!
Dennis

**Comment by raviks789** [comment]
@dmueckli, could you also share your Jira Software version? if the version is above 9.x.x then the pull request #89 solves this issue.

**Comment by dmueckli** [comment]
Jira software is indeed above 9.x.x, thanks a lot!
