### ISSUE TITLE
No Permissions for Administrative Role

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2-module-jira#86]
Hi all,
we just noticed, that a role is not able to use the jira module, although the role has administrative access and all permissions for the jira module, see screenshot below:
![image](https://user-images.githubusercontent.com/7324088/182369832-1ef98425-e4f3-4e60-b1a9-6720c454078f.png)

This role has only an object filter defined, what should not affect the jira module. Whether the jira menu in the sidebar nor the action item for issue creating appears. 
Testing by calling a jira issue create url, I get the following stacktrace:

```
No permission for module/jira

#0 /usr/share/php/Icinga/Web/Controller/ModuleActionController.php(31): Icinga\Web\Controller\ActionController->assertPermission()
#1 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/CompatController.php(44): Icinga\Web\Controller\ModuleActionController->prepareInit()
#2 /usr/share/php/Icinga/Web/Controller/ActionController.php(169): ipl\Web\Compat\CompatController->prepareInit()
#3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#5 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#6 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#7 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#8 {main}
```

Module Version is 1.2.2
We are currently running IDO and IcingaDB backend in parallel. 

Cheers,
Marcus

**Comment by MarcusCaepio** [comment]
Sorry, found the problem. Overwrite of another role, I close the issue
